# Generated by Django 3.1.6 on 2021-03-23 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=21)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=21)),
                ('left', models.DecimalField(decimal_places=20, max_digits=21)),
                ('down', models.DecimalField(decimal_places=20, max_digits=21)),
                ('right', models.DecimalField(decimal_places=20, max_digits=21)),
                ('up', models.DecimalField(decimal_places=20, max_digits=21)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinkCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField(choices=[(1, 'Tripadvisor'), (2, 'Booking')])),
                ('value', models.CharField(max_length=150)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartapi.city')),
            ],
        ),
        migrations.DeleteModel(
            name='Citie',
        ),
    ]
