# Generated by Django 3.1.6 on 2021-03-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapi', '0002_auto_20210322_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='down',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
        migrations.AlterField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
        migrations.AlterField(
            model_name='city',
            name='left',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
        migrations.AlterField(
            model_name='city',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
        migrations.AlterField(
            model_name='city',
            name='right',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
        migrations.AlterField(
            model_name='city',
            name='up',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
    ]
