# Generated by Django 3.1.6 on 2021-03-26 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartapi', '0003_auto_20210322_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('priority', models.IntegerField()),
                ('distance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('isprincipal', models.BooleanField()),
                ('characteristic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='smartapi.characteristic')),
            ],
        ),
        migrations.AlterField(
            model_name='linkcity',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='smartapi.city'),
        ),
        migrations.CreateModel(
            name='ValueCharacteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='smartapi.characteristic')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='smartapi.characteristic')),
            ],
        ),
    ]
