# Generated by Django 3.1.6 on 2021-03-26 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartapi', '0004_auto_20210325_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characteristic',
            old_name='characteristic_id',
            new_name='characteristic',
        ),
    ]
