# Generated by Django 3.1.6 on 2021-03-26 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartapi', '0005_auto_20210325_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='characteristic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='smartapi.characteristic'),
        ),
    ]
