# Generated by Django 3.1.6 on 2021-04-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapi', '0011_auto_20210414_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tweet_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
