# Generated by Django 3.1.6 on 2021-04-14 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartapi', '0012_tweet_tweet_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertweet',
            old_name='usuarios_id',
            new_name='user_id',
        ),
    ]
